# Rutas de mi Aplicación
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Rutas de FOS_USER
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin